// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSupabaseAnonKey, getDirectSupabaseUrl, getSupabaseStorageKey, getSupabaseUrl } from './config';

const SUPABASE_URL = getSupabaseUrl();
const DIRECT_SUPABASE_URL = getDirectSupabaseUrl();
const SUPABASE_PUBLISHABLE_KEY = getSupabaseAnonKey();
const SUPABASE_STORAGE_KEY = getSupabaseStorageKey();

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing Supabase environment variables. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your .env file.'
  );
}

/**
 * Lock processor "in-memory" — substitui o Web Locks API global do Supabase.
 * Evita NavigatorLockAcquireTimeoutError quando há múltiplas abas abertas
 * (cada aba processa seu próprio lock sem brigar pela exclusividade global).
 */
function inMemoryLock<R>(_name: string, _acquireTimeout: number, fn: () => Promise<R>) {
  return fn();
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      storageKey: SUPABASE_STORAGE_KEY,
      persistSession: true,
      autoRefreshToken: true,
      lock: inMemoryLock,
    }
  });

// Vercel rewrites não suportam WebSocket, então o realtime precisa apontar
// direto para o host do Supabase mesmo quando REST/Auth passam pelo same-origin proxy.
if (DIRECT_SUPABASE_URL && SUPABASE_URL !== DIRECT_SUPABASE_URL) {
  try {
    const wsUrl = DIRECT_SUPABASE_URL.replace(/^http/, 'ws') + '/realtime/v1/websocket';
    (supabase.realtime as unknown as { endPoint: string }).endPoint = wsUrl;
  } catch {
    // noop — fallback ao default
  }
}
